FROM node:14.21.3-slim AS builder

WORKDIR /usr/share/nginx/html

COPY package.json ./

RUN npm install --silent

COPY ./ ./

RUN npm run build

FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html

COPY --from=builder /usr/share/nginx/html ./

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

ENTRYPOINT ["nginx", "-g", "daemon off;"]

