FROM node:14.21.3-slim AS builder

WORKDIR /app

COPY . .

RUN npm install --silent

RUN npm run build

FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/build ./

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000