version: '3'

networks:
  react:

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    image: react/react-nginx
    container_name: react-nginx
    tty: true
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:3000
    working_dir: /usr/share/nginx/html
    restart: unless-stopped
    networks:
      - react
