version: '3'

services:
  instagram-client:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: instagram-client
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
